- name: title
  type: VARCHAR
- name: submission_id
  type: VARCHAR
- name: subreddit_id
  type: VARCHAR
- name: created_ts
  type: float
- name: banned_at_utc
  type: float
- name: url
  type: VARCHAR
- name: num_comments
  type: int
- name: ups
  type: int
- name: downs
  type: int
- name: over_18
  type: bool
- name: removal_reason
  type: VARCHAR
- name: report
  type: VARCHAR
- name: num_reports
  type: int
- name: author
  type: VARCHAR
- name: author_comment_karma
  type: VARCHAR
- name: author_link_karma
  type: VARCHAR